services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev --features=quick-theme
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - ./themes:/opt/keycloak/themes